# Generated by Django 4.2.27 on 2026-01-06 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(choices=[('veg_menu', 'Vegetarian Menu'), ('non_veg_menu', 'Non-Vegetarian Menu'), ('desserts', 'Desserts'), ('beverages', 'Beverages'), ('live_counter', 'Live Counter'), ('buffet', 'Buffet Package')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_plate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuisine_type', models.CharField(help_text='Indian, Chinese, Continental, etc.', max_length=100)),
                ('serves', models.IntegerField(default=1, help_text='Number of people')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(choices=[('bridal_set', 'Bridal Set'), ('necklace', 'Necklace'), ('earrings', 'Earrings'), ('bangles', 'Bangles'), ('maang_tikka', 'Maang Tikka'), ('nose_ring', 'Nose Ring')], max_length=50)),
                ('description', models.TextField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(help_text='Gold, Silver, Kundan, etc.', max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='jewellery/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Jewellery Items',
                'ordering': ['subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subcategory', models.CharField(choices=[('banquet_hall', 'Banquet Hall'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('garden', 'Garden'), ('farmhouse', 'Farmhouse'), ('convention_center', 'Convention Center')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(help_text='Maximum guest capacity')),
                ('location', models.CharField(max_length=200)),
                ('features', models.TextField(help_text='Features separated by new lines')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subcategory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.venueitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JewelleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='jewellery/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('jewellery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.jewelleryitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.fooditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('venue', 'Venue'), ('jewellery', 'Jewellery'), ('food', 'Food')], max_length=20)),
                ('item_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'item_type', 'item_id')},
            },
        ),
    ]
